#
# PATH	:	/home/$USER/any_dir
#
# TYPE	:	overlay | tmpfs
#
# <PATH>							                        <TYPY>
/home/xxx/.android/avd			                             tmpfs
/home/xxx/.android/cache			                         tmpfs
/home/xxx/.android/studio/config/tasks			             tmpfs
/home/xxx/.android/studio/config/workspace		             tmpfs
/home/xxx/.cache                                             tmpfs
/home/xxx/.config/Code			                             overlay	
/home/xxx/.config/GIMP				                         tmpfs
/home/xxx/.config/google-chrome		                         overlay
/home/xxx/.config/pulse			                             tmpfs
/home/xxx/.dart					            		         tmpfs
/home/xxx/.dartServer				                         tmpfs
/home/xxx/.dart-tool				                         tmpfs
/home/xxx/.dotnet						                     tmpfs
/home/xxx/.java				                                 tmpfs
/home/xxx/.javacpp						                     tmpfs
/home/xxx/.local/share						                 overlay
/home/xxx/.m2							                     tmpfs
/home/xxx/.pki							                     tmpfs
/home/xxx/.skiko						                     tmpfs
/home/xxx/.files/Linux/SDK/Android/.downloadIntermediates    tmpfs
/home/xxx/.files/Linux/SDK/Android/.temp	                 tmpfs
/home/xxx/Screencasts						                 tmpfs
/home/xxx/Screenshots						                 tmpfs
