#!/bin/bash

set -Eeuxo pipefail

MACHINE_NAME="test"
QEMU_IMG="${MACHINE_NAME}.img"
SSH_PORT="5555"
OVMF_CODE="/usr/share/OVMF/OVMF_CODE_4M.ms.fd"
OVMF_VARS_ORIG="/usr/share/OVMF/OVMF_VARS_4M.ms.fd"
OVMF_VARS="$HOME/.cache/$(basename "${OVMF_VARS_ORIG}")"

if [ ! -e "${QEMU_IMG}" ]; then
        qemu-img create -f qcow2 "${QEMU_IMG}" 100G
fi

# if [ ! -e "${OVMF_VARS}" ]; then
#         cp "${OVMF_VARS_ORIG}" "/home/xxx/.cache/${OVMF_VARS}"
# fi
cp "${OVMF_VARS_ORIG}" "${OVMF_VARS}"


# qemu-system-x86_64 \
#         -enable-kvm \
#         -cpu host -smp cores=4,threads=1 -m 4096 \
#         -object rng-random,filename=/dev/urandom,id=rng0 \
#         -device virtio-rng-pci,rng=rng0 \
#         -name "${MACHINE_NAME}" \
#         -drive file="${QEMU_IMG}",format=qcow2 \
#         -net nic,model=virtio -net user,hostfwd=tcp::${SSH_PORT}-:22 \
#         -vga virtio \
#         -machine q35,smm=on \
#         -global driver=cfi.pflash01,property=secure,value=on \
#         -drive if=pflash,format=raw,unit=0,file="${OVMF_CODE}",readonly=on \
#         -drive if=pflash,format=raw,unit=1,file="${OVMF_VARS}" \
#         -drive file=/dev/sdd,format=raw,media=disk \
#         -cdrom /tmp/debian-live-12.0.0-amd64-mate.iso \
#         $@

qemu-system-x86_64 \
        -enable-kvm \
        -cpu host -smp $(nproc) -m 4096 \
        -object rng-random,filename=/dev/urandom,id=rng0 \
        -device virtio-rng-pci,rng=rng0 \
        -name "${MACHINE_NAME}" \
        -drive file="${QEMU_IMG}",format=qcow2 \
        -net nic,model=virtio -net user,hostfwd=tcp::${SSH_PORT}-:22 \
        -vga virtio \
        -machine q35,smm=on \
        -global driver=cfi.pflash01,property=secure,value=on \
        -drive if=pflash,format=raw,unit=0,file="${OVMF_CODE}",readonly=on \
        -drive if=pflash,format=raw,unit=1,file="${OVMF_VARS}" \
        -boot order=c,menu=on \
        $@