# required pulseaudio-utils
# context.exec = [
# 	# Creates a device where AudioRelay can stream audio into
# 	{ 
# 		path = "pactl"
# 		args = "load-module module-null-sink sink_name=audiorelay-virtual-mic-sink sink_properties=device.description=Virtual-Mic-Sink"
# 	}
# 	# Creates a device usable by communications apps (e.g: skype)
# 	{ 
#         path = "pactl"
#         args = "load-module module-remap-source master=audiorelay-virtual-mic-sink.monitor source_name=audiorelay-virtual-mic-sink source_properties=device.description=Virtual-Mic"
#     }
# ]
