# pass a new line for the last input
# otherwise the last input will not be read
/home/xxx/.android/avd
/home/xxx/.android/cache
/home/xxx/.android/studio/config/tasks
/home/xxx/.android/studio/config/workspace
/home/xxx/.cache
/home/xxx/.config/GIMP
/home/xxx/.config/pulse
/home/xxx/.dart
/home/xxx/.dartServer
/home/xxx/.dart-tool
/home/xxx/.dotnet
/home/xxx/.java
/home/xxx/.javacpp
/home/xxx/.m2
/home/xxx/.npm
/home/xxx/.pki
/home/xxx/.pub-cache
/home/xxx/.skiko
/home/xxx/.files/Linux/SDK/Android/.downloadIntermediates
/home/xxx/.files/Linux/SDK/Android/.temp
/home/xxx/.files/Linux/SDK/Android/system-images
#
