name: base_system_bookworm

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  base_system:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
          matrix:
            arch:
              - amd64
              - arm64
    env:
      DEBIAN_FRONTEND: noninteractive
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ROOTFS_DIR: ${{ github.workspace }}/rootfs_dir
      ARCH: ${{ matrix.arch }}
      CODENAME: bookworm
    
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4

      - name: SETUP DEBOOTSTRAP WITH DOCKER
        run: |
          _DOCKER_IMAGE="debian:$CODENAME"
          _PLATFORM="linux/$ARCH"
          _ARCH_HOST=$(dpkg --print-architecture)
          if [ $_ARCH_HOST != $ARCH ]; then
            sudo apt install --no-install-suggests --no-install-recommends qemu binfmt-support qemu-user-static -y 2>&1 >/dev/null
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          fi
          docker pull --platform $_PLATFORM $_DOCKER_IMAGE
          c_name=x-000
          mkdir -pv $ROOTFS_DIR
          ROOTFS_DIR_NAME=$(basename $ROOTFS_DIR)
          docker create --name "$c_name" --privileged -e "DEBIAN_FRONTEND=noninteractive" -v "$ROOTFS_DIR:/$ROOTFS_DIR_NAME" --entrypoint "tail" --platform "$_PLATFORM" "$_DOCKER_IMAGE" -f /dev/null
          docker start $c_name
          docker exec $c_name apt-get update 2>&1 >/dev/null
          docker exec $c_name apt-get upgrade --no-install-suggests --no-install-recommends -y 2>&1 >/dev/null
          docker exec $c_name apt-get install --no-install-suggests --no-install-recommends apt-utils debootstrap -y 2>&1 >/dev/null
          export INCLUDE_PACKAGE="apt-utils,bash-completion,whiptail"
          export EXCLUDE_PACKAGE="e2fsprogs,sysvinit-utils"
          docker exec $c_name debootstrap --variant=minbase --arch $ARCH --exclude=$EXCLUDE_PACKAGE --include=$INCLUDE_PACKAGE $CODENAME /$ROOTFS_DIR_NAME http://deb.debian.org/debian
      
      - name: CLEAN UP USELESS FOLDERS
        run: |
          dirs="dev etc/.pwd.lock root run var/cache var/lib/apt var/log"
          for dir in $dirs; do
            if [ -f "$ROOTFS_DIR/$dir" ]; then
              sudo rm -rfv $ROOTFS_DIR/$dir
              continue
            fi
            for i in $(sudo ls -A $ROOTFS_DIR/$dir 2>/dev/null); do
              sudo rm -rfv $ROOTFS_DIR/$dir/$i
            done
          done
      
      - name: SETUP HOSTNAME
        run: |
          cat << "EOF" | sudo tee $ROOTFS_DIR/etc/hostname
          x-host
          EOF
      
      - name: SETUP HOSTS
        run: |
          cat << EOF | sudo tee $ROOTFS_DIR/etc/hosts
          127.0.0.1       localhost $(cat /etc/hostname) $(cat /etc/hostname).co.id
          ::1             localhost $(cat /etc/hostname) $(cat /etc/hostname).co.id ip6-localhost ip6-loopback
          fe00::0         ip6-localnet
          ff00::0         ip6-mcastprefix
          ff02::1         ip6-allnodes
          ff02::2         ip6-allrouters
          EOF
      
      - name: SETUP RESOLV CONF
        run: |
          cat << "EOF" | sudo tee $ROOTFS_DIR/etc/resolv.conf
          nameserver 8.8.8.8
          nameserver 8.8.4.4
          EOF
      
      - name: SETUP SOURCE LIST
        run: |
          cat << EOF | sudo tee $ROOTFS_DIR/etc/apt/sources.list &>/dev/null
          deb http://deb.debian.org/debian               bookworm           main contrib non-free non-free-firmware
          deb http://security.debian.org/debian-security bookworm-security  main contrib non-free non-free-firmware
          deb http://deb.debian.org/debian               bookworm-updates   main contrib non-free non-free-firmware
          deb http://deb.debian.org/debian               bookworm-backports main contrib non-free non-free-firmware
          EOF

      - name : SETUP BASH BASHRC
        run: |
          cat << "EOF" | sudo tee $ROOTFS_DIR/etc/bash.bashrc
          [ -z "$PS1" ] && return

          shopt -s checkwinsize

          if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
            debian_chroot=$(cat /etc/debian_chroot)
          fi

          if ! [ -n "${SUDO_USER}" -a -n "${SUDO_PS1}" ]; then
            PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
          fi

          if ! shopt -oq posix; then
            . /usr/share/bash-completion/bash_completion
          fi
          EOF
      
      - name : SETUP LOCALE
        run: |
          cat << EOF | sudo tee $ROOTFS_DIR/etc/default/locale
          LANG=C.UTF-8
          LANGUAGE=C.UTF-8
          LC_ADDRESS=C.UTF-8
          LC_ALL=C.UTF-8
          LC_COLLATE=C.UTF-8
          LC_CTYPE=C.UTF-8
          LC_IDENTIFICATION=C.UTF-8
          LC_MEASUREMENT=C.UTF-8
          LC_MESSAGES=C.UTF-8
          LC_MONETARY=C.UTF-8
          LC_NAME=C.UTF-8
          LC_NUMERIC=C.UTF-8
          LC_PAPER=C.UTF-8
          LC_TELEPHONE=C.UTF-8
          LC_TIME=C.UTF-8
          EOF

      - name : SETUP KEYBOARD
        run: |
          cat << EOF | sudo tee $ROOTFS_DIR/etc/default/keyboard
          XKBLAYOUT=us
          EOF

      - name : SETUP KEYMAP
        run: |
          cat << EOF | sudo tee $ROOTFS_DIR/etc/vconsole.conf
          KEYMAP=us
          EOF

      - name: SETUP WITH CHROOT
        run: |
          # MOUNT BEGIN
          sudo mount -v udev     -t devtmpfs $ROOTFS_DIR/dev         -o defaults,size=0
          sudo mount -v devpts   -t devpts   $ROOTFS_DIR/dev/pts     -o defaults
          sudo mount -v tmpfs    -t tmpfs    $ROOTFS_DIR/media       -o defaults,size=100%,nr_inodes=0,mode=0775
          sudo mount -v tmpfs    -t tmpfs    $ROOTFS_DIR/mnt         -o defaults,size=100%,nr_inodes=0,mode=0775
          sudo mount -v proc     -t proc     $ROOTFS_DIR/proc        -o defaults
          sudo mount -v tmpfs    -t tmpfs    $ROOTFS_DIR/root        -o defaults,size=100%,nr_inodes=0,mode=0700
          sudo mount -v tmpfs    -t tmpfs    $ROOTFS_DIR/run         -o defaults,size=100%,nr_inodes=0,mode=0775
          sudo mkdir -p $ROOTFS_DIR/run/lock
          sudo mount -v tmpfs    -t tmpfs    $ROOTFS_DIR/run/lock    -o defaults,size=100%,nr_inodes=0,nosuid,nodev,noexec
          sudo mount -v sysfs    -t sysfs    $ROOTFS_DIR/sys         -o defaults
          sudo mount -v tmpfs    -t tmpfs    $ROOTFS_DIR/tmp         -o defaults,size=100%,nr_inodes=0,mode=1777,nosuid,nodev
          sudo mount -v tmpfs    -t tmpfs    $ROOTFS_DIR/var/cache   -o defaults,size=100%,nr_inodes=0,mode=0755
          sudo mount -v tmpfs    -t tmpfs    $ROOTFS_DIR/var/lib/apt -o defaults,size=100%,nr_inodes=0,mode=0755
          sudo mount -v tmpfs    -t tmpfs    $ROOTFS_DIR/var/log     -o defaults,size=100%,nr_inodes=0,mode=0755
          sudo chroot                        $ROOTFS_DIR
          # MOUNT END

          # CHROOT BEGIN
          sudo chroot $ROOTFS_DIR /bin/bash <<"EOF_CHROOT"
          
          # DPKG Conf
          cat << EOF > /etc/dpkg/dpkg.cfg.d/x-dpkg
          force-unsafe-io
          path-exclude=/usr/share/doc/*
          path-exclude=/usr/share/man/*
          path-exclude=/usr/share/info/*
          path-exclude=/usr/share/lintian/*
          path-exclude=/usr/share/locale/*
          path-include=/usr/share/locale/en*
          EOF
          
          # DPKG Clear Path Exclude
          for _paths in $(sed -n 's|path-[a-z]*=\(/[^/]*\(/[^/]*\)*\)/.*|\1|p' /etc/dpkg/dpkg.cfg.d/x-dpkg | uniq); do
            for _path in $(ls -A "$_paths"); do
              rm -rfv "$_paths/$_path"
            done
          done

          # REINSTALL ALL PACKAGE
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          packages=$(dpkg --get-selections | grep -v deinstall | awk '{print $1}')
          apt-get install --no-install-recommends --no-install-suggests --reinstall $packages -y 2>&1 >/dev/null
          echo "$packages" | wc -l
          EOF_CHROOT
          # CHROOT END

          # REMOVE PWD LOCK IF EXISTS
          [ -f $ROOTFS_DIR/etc/.pwd.lock ] && rm -rfv $ROOTFS_DIR/etc/.pwd.lock

          # UMOUNT BEGIN
          for dir in $(mount | grep "$ROOTFS_DIR/" | awk '{print $3}'); do
            mount | grep -q "on $dir type" && sudo umount -v --recursive $dir
          done
          # UMOUNT END

      - name: MAKE ARTIFACT
        run: |
          sudo apt install xz-utils -y
          cd $ROOTFS_DIR && sudo tar --use-compress-program='xz -9' -cvf /tmp/rootfs_${ARCH}.tar.xz * > /tmp/rootfs_${ARCH}.tar.txt

      - name: UPLOAD ARTIFACT
        run: |
          _title="base_system_debian-$(cat $ROOTFS_DIR/etc/debian_version)-$ARCH"
          _resources="/tmp/rootfs_${ARCH}.tar.xz /tmp/rootfs_${ARCH}.tar.txt"
          _tag="${_title}-tag"
          gh release delete $_tag --cleanup-tag --yes || true
          gh release create "$_tag" $_resources --generate-notes --title "$_title" --latest